### ISSUE TITLE
Outdated aiohttp version for pycarwings3 in 2024.12.0b1

### ISSUE THREAD

**Issue by Arquiteto** [remuslazar/homeassistant-carwings#70]
## System Information

version | core-2024.12.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1483
Downloaded Repositories | 70

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 stycznia 2018 01:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | null
certificate_status | null
instance_id | 62d6cf8d59e1415d8d27954de8d614c0
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 146.9 GB
disk_used | 138.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (5.1.2), Advanced SSH & Web Terminal (19.0.0), Bambu Lab P1 - Spaghetti Detection Server (1.0.0), Cloudflared (5.2.1), ESPHome (2024.9.0), File editor (5.8.0), Frigate Proxy (1.5), Grafana (10.2.2), Home Assistant Google Drive Backup (0.112.1), JupyterLab (0.15.5), Let's Encrypt (5.1.4), Mosquitto broker (6.4.1), NGINX Home Assistant SSL proxy (3.10.1), Piper (1.5.2), Samba share (12.3.2), Terminal & SSH (9.14.0), Tesla HTTP Proxy (2.2.8), Whisper (2.1.2), ZeroTier One (0.18.0), Zigbee2MQTT (1.41.0-1), chrony (4.0.0), evcc (0.131.4), phpMyAdmin (0.10.0), MariaDB (2.7.1), InfluxDB (5.0.0), Log Viewer (0.17.0), openWakeWord (1.10.0), Studio Code Server (5.17.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 35
views | 37
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 listopada 2024 18:58
-- | --
current_recorder_run | 28 listopada 2024 14:13
estimated_db_size | 13331.59 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Pycarwings3 requires aiohttp<3.11 and HA 2024.12 has aiohttp 3.11.8 resulting in requirements conflict

### Reproduction steps

1. Install HA >= 2024.12.0b0

### Debug logs

```text
Unable to install package pycarwings3~=0.7.8: × No solution found when resolving dependencies: ╰─▶ Because pycarwings3==0.7.8 depends on aiohttp>=3.10.1,<3.11.dev0 and aiohttp==3.11.8, we can conclude that pycarwings3==0.7.8 cannot be used. And because only pycarwings3<=0.7.8 is available and you require pycarwings3>=0.7.8, we can conclude that your requirements are unsatisfiable. hint: pycarwings3 was requested with a pre-release marker (e.g., pycarwings3>0.7.8,<0.8.dev0), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

**Comment by remuslazar** [comment]
@Arquiteto thank you for this issue. I have fixed the issue in the related pycarwings3 library. Could you please verify it this also fixes the issue in your case? It should install 0.7.9 now.

**Comment by Arquiteto** [comment]
It's not fixed

`Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 15:29:24 (3 occurrences)
Last logged: 15:29:26

Unable to install package pycarwings3~=0.7.9: × No solution found when resolving dependencies: ╰─▶ Because pycarwings3==0.7.9 depends on aiohttp>=3.10.1,<3.11.dev0 and aiohttp==3.11.8, we can conclude that pycarwings3==0.7.9 cannot be used. And because only pycarwings3<=0.7.9 is available and you require pycarwings3>=0.7.9, we can conclude that your requirements are unsatisfiable. hint: pycarwings3 was requested with a pre-release marker (e.g., pycarwings3>0.7.9,<0.8.dev0), but pre-releases weren't enabled (try: `--prerelease=allow`)`

My HA apparently has aiohttp==3.11.8. Not sure if it's core requirement or a colision with some other custom component.

**Comment by Arquiteto** [comment]
aiohttp==3.11.8 is HA core 2024.12 requirement

**Comment by remuslazar** [comment]
@Arquiteto ok, I see.. could you please try it again now, it should install 0.7.10 without issues. Thanks!

**Comment by Arquiteto** [comment]
With 0.7.10 it was not working, but I saw the update to 0.7.11 and tried that one.

I had to edit the manifest.json to:
```
  "requirements": [
    "pycarwings3~=0.7.11"
  ],
```
With pycarwings3~=0.7.10 it wouldn't work, becasue it still wanted to load 0.7.10 (which is strange, because I tought this marker would load the latest version lower than 0.8.x)

**Comment by remuslazar** [comment]
@Arquiteto yeah, the 0.7.10 was buggy, I have released 0.7.11 afterwards. Everything should work out of the box without any changes to manifest.json. Could u please try that?

**Comment by Arquiteto** [comment]
Ok, I can confirm it works with ~=0.7.8 too.
